jobs:

  - name: wifi-location-sensing-server-manifest
    type: manifest
    steps:
      - IN: wifi-location-sensing-server-image
      - IN: wifi-location-sensing-server-docker-options
      - TASK: managed

  - name: wifi-location-sensing-server-deploy
    type: deploy
    steps:
      - IN: wifi-location-sensing-server-manifest
      - IN: wifi-location-sensing-server-test-ecs-cluster
      - TASK: managed
        deployMethod: replace
