jobs:
  - name: wifi-location-sensing-server-manifest
    type: manifest
    steps:
     - IN: wifi-location-sensing-server-image
     - TASK: managed

  - name: deploy-wifi-location-sensing-server
    type: deploy
    steps:
      - IN: wifi-location-sensing-server-manifest
      - IN: docker-options
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade
