jobs:

  - name: wifi-location-sensing-server-manifest
    type: manifest
    steps:
      - IN: dv-img2
      - IN: dv-img-opts2
      - TASK: managed

  - name: wifi-location-sensing-server-deply
    type: deploy
    steps:
      - IN: wifi-location-sensing-server-manifest
#      - IN: dv-params
      - IN: env-test-ecs3
      - TASK: managed
