jobs:

  - name: wifi-location-sensing-server-manifest
    type: manifest
    steps:
      - IN: wifi-location-sensing-server-image
      - TASK: managed

  - name: wifi-location-sensing-server-deploy
    type: deploy
    steps:
      - IN: wifi-location-sensing-server-manifest
        force: true
      - IN: wifi-location-sensing-server-test-ecs-cluster
      - TASK: managed
